name: Docker Build and Push to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JF_URL }}
          username: eytanr
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ARTIFACTORY_REGISTRY }}/eytanr-docker/docker
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            idani.jfrog.io/eytanr-docker/docker-example:latest
            idani.jfrog.io/eytanr-docker/docker-example:${{ github.sha }}
